### ISSUE TITLE
evaluation results difference

### ISSUE THREAD

**Issue by kimwongyuda** [studio-ousia/ease#6]
Thank you for your amazing projects and codes.

When I implemented your codes by using the command "python evaluation.py --model_name_or_path sosuke/ease-bert-base-uncased --pooler avg --task_set sts",
I found there is difference between results of paper and implementation like below.

![image](https://github.com/studio-ousia/ease/assets/35097915/3c1f704f-a340-4e4f-a265-ef94138465ef)
![image](https://github.com/studio-ousia/ease/assets/35097915/f2cdc165-520c-4175-81fb-df0e2e17a24c)

Could you tell me what i might have missed, which affects that difference?

Thank you!

**Comment by kimwongyuda** [comment]
I also found that some API calls result in 302/404 errors like below.
It can lead to that difference?

**2023-05-25 05:37:31,355 : Starting new HTTPS connection (1): huggingface.co:443
2023-05-25 05:37:31,912 : https://huggingface.co:443 "HEAD /sosuke/ease-bert-base-uncased/resolve/main/pytorch_model.bin HTTP/1.1" 302 0
2023-05-25 05:37:35,370 : Starting new HTTPS connection (1): huggingface.co:443
2023-05-25 05:37:36,144 : https://huggingface.co:443 "HEAD /sosuke/ease-bert-base-uncased/resolve/main/added_tokens.json HTTP/1.1" 404 0**

![image](https://github.com/studio-ousia/ease/assets/35097915/8c649431-31bf-4455-ab1a-9f5e5a883c21)

**Comment by kimwongyuda** [comment]
I solved the issue by using difference pooler.

**Comment by Sosuke115** [comment]
Seems your issue is fixed.
